"use client"

import type { AuctionItem } from "@/app/auction/page"

export const featuredItem: AuctionItem = {
  id: "featured-1",
  title: "Inabel Heritage Weave - Museum Grade",
  artisan: "Maestro Lilia Domingo",
  artisanImage: "/images/auction/elderly-filipino-woman-weaver-portrait.jpg",
  image: "/images/auction/beautiful-intricate-inabel-textile-weaving-traditi.jpg",
  currentBid: 45000,
  startingBid: 25000,
  bids: 23,
  timeLeft: { days: 0, hours: 4, minutes: 32, seconds: 15 },
  isLimited: true,
  edition: "1 of 1",
  description:
    "A masterpiece hand-woven over 6 months using traditional Ilocano techniques passed down through five generations.",
  category: "Textiles",
}

export const liveAuctions: AuctionItem[] = [
  {
    id: "1",
    title: "Capiz Shell Wind Chime",
    artisan: "Elena Magsaysay",
    artisanImage: "/images/auction/filipino-artisan-woman-portrait.jpg",
    image: "/images/auction/beautiful-capiz-shell-wind-chime-handcrafted-iride.jpg",
    currentBid: 3500,
    startingBid: 2000,
    bids: 12,
    timeLeft: { days: 1, hours: 20, minutes: 45, seconds: 30 },
    isLimited: true,
    edition: "3 of 10",
    description: "Handcrafted Capiz shell wind chime from Aklan province.",
    category: "Home Decor",
  },
  {
    id: "2",
    title: "Hand-carved Ifugao Bulul",
    artisan: "Pedro Maclang",
    artisanImage: "/images/auction/pedro-maclang.jpg",
    image: "/images/auction/wooden-ifugao-bulul-rice-god-carved-sculpture-trad.jpg",
    currentBid: 15800,
    startingBid: 10000,
    bids: 8,
    timeLeft: { days: 0, hours: 8, minutes: 22, seconds: 10 },
    isLimited: true,
    edition: "1 of 5",
    description: "Traditional Ifugao rice god carved from narra wood.",
    category: "Sculptures",
  },
  {
    id: "3",
    title: "Binakol Woven Blanket",
    artisan: "Rosa Villanueva",
    artisanImage: "/images/auction/rosa-villanueva.jpg",
    image: "/images/auction/binakol-woven-blanket-geometric-pattern-traditiona.jpg",
    currentBid: 8200,
    startingBid: 5000,
    bids: 15,
    timeLeft: { days: 2, hours: 14, minutes: 55, seconds: 45 },
    isLimited: true,
    edition: "2 of 8",
    description: "Traditional Binakol blanket with optical illusion patterns.",
    category: "Textiles",
  },
  {
    id: "4",
    title: "Burnay Pottery Set",
    artisan: "Juan dela Cruz",
    artisanImage: "/images/auction/filipino-potter-man-portrait.jpg",
    image: "/images/auction/burnay-pottery-traditional-ilocos-clay-jars-terrac.jpg",
    currentBid: 4500,
    startingBid: 3000,
    bids: 6,
    timeLeft: { days: 0, hours: 3, minutes: 12, seconds: 8 },
    isLimited: true,
    edition: "5 of 12",
    description: "Traditional Ilocano clay pottery set for fermenting.",
    category: "Pottery",
  },
]
